// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBP8-g05MQUGUPcev10Y86cO57nBUf10s',
    appId: '1:889392669151:web:88a94a80006d8c1198646a',
    messagingSenderId: '889392669151',
    projectId: 'colorist-90e31',
    authDomain: 'colorist-90e31.firebaseapp.com',
    storageBucket: 'colorist-90e31.firebasestorage.app',
    measurementId: 'G-ZNXS00PV51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXDLvXv6t4wWjgDM2MMnRbj3-6MflLec',
    appId: '1:889392669151:android:5d132bc63452e43498646a',
    messagingSenderId: '889392669151',
    projectId: 'colorist-90e31',
    storageBucket: 'colorist-90e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyg5Klx6bgbr_BDKcOdp9MlaqGiormwYI',
    appId: '1:889392669151:ios:20280791a6f0645b98646a',
    messagingSenderId: '889392669151',
    projectId: 'colorist-90e31',
    storageBucket: 'colorist-90e31.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyg5Klx6bgbr_BDKcOdp9MlaqGiormwYI',
    appId: '1:889392669151:ios:20280791a6f0645b98646a',
    messagingSenderId: '889392669151',
    projectId: 'colorist-90e31',
    storageBucket: 'colorist-90e31.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBP8-g05MQUGUPcev10Y86cO57nBUf10s',
    appId: '1:889392669151:web:1e8ff0f6b44d2e7f98646a',
    messagingSenderId: '889392669151',
    projectId: 'colorist-90e31',
    authDomain: 'colorist-90e31.firebaseapp.com',
    storageBucket: 'colorist-90e31.firebasestorage.app',
    measurementId: 'G-45J7FN1SPW',
  );
}
